Asistencia.Mvc/Controllers/HorarioController.cs
using Asistencia.Models;
using Asistencia.Repositories.Dapper.Asistencia;
using Asistencia.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asistencia.Mvc.Controllers
{
    public class HorarioController : BaseController
    {
        public HorarioController(IUnitOfWork unit) : base(unit)
        {

        }
        // GET: Horario
        public ActionResult Index()
        {
            return View(_unit.Horario.GetList());
        }

        public ActionResult Create()
        {
            return View(new Horario());
        }

        [HttpPost]
        public ActionResult Create(Horario horario)
        {
            if (ModelState.IsValid)
            {
                _unit.Horario.Insert(horario);
                return RedirectToAction("Index");
            }
            return View(horario);
        }

        public ActionResult Edit(int id)
        {
            return View(_unit.Horario.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(Horario horario)
        {
            if (_unit.Horario.Update(horario))
            {
                return RedirectToAction("Index");
            }
            return View(horario);
        }

        public ActionResult Delete(int id)
        {
            return View(_unit.Horario.GetById(id));
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (_unit.Horario.Delete(id))
            {
                return RedirectToAction("Index");
            }
            return View(_unit.Horario.GetById(id));
        }
    }
}

Asistencia.Mvc/Controllers/OficinaController.cs
using Asistencia.Models;
using Asistencia.Repositories.Dapper.Asistencia;
using Asistencia.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asistencia.Mvc.Controllers
{
    public class OficinaController : BaseController
    {
        public OficinaController(IUnitOfWork unit): base(unit)
        {
 
        }
        // GET: Oficina
        public ActionResult Index()
        {
            return View(_unit.Oficina.GetList());
        }

        public ActionResult Create()
        {
            return View(new Oficina());
        }

        [HttpPost]
        public ActionResult Create(Oficina oficina)
        {
            if (ModelState.IsValid)
            {
                _unit.Oficina.Insert(oficina);
                return RedirectToAction("Index");
            }
            return View(oficina);
        }

        public ActionResult Edit(int id)
        {
            return View(_unit.Oficina.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(Oficina oficina)
        {
            if (_unit.Oficina.Update(oficina))
            {
                return RedirectToAction("Index");
            }
            return View(oficina);
        }

        public ActionResult Delete(int id)
        {
            return View(_unit.Oficina.GetById(id));
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (_unit.Oficina.Delete(id))
            {
                return RedirectToAction("Index");
            }
            return View(_unit.Oficina.GetById(id));
        }
    }
}

Asistencia.Mvc/Controllers/TipoDocIdentidadController.cs
using Asistencia.Models;
using Asistencia.Repositories.Dapper.Asistencia;
using Asistencia.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asistencia.Mvc.Controllers
{
    public class TipoDocIdentidadController : BaseController
    {
        public TipoDocIdentidadController(IUnitOfWork unit): base(unit)
        {

        }
        // GET: TipoDocIdentidad
        public ActionResult Index()
        {
            return View(_unit.TipoDocIdentidad.GetList());
        }

        public ActionResult Create()
        {
            return View(new TipoDocIdentidad());
        }

        [HttpPost]
        public ActionResult Create(TipoDocIdentidad tipoDocIdentidad)
        {
            if (ModelState.IsValid)
            {
                _unit.TipoDocIdentidad.Insert(tipoDocIdentidad);
                return RedirectToAction("Index");
            }
            return View(tipoDocIdentidad);
        }

        public ActionResult Edit(int id)
        {
            return View(_unit.TipoDocIdentidad.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(TipoDocIdentidad tipoDocIdentidad)
        {
            if (_unit.TipoDocIdentidad.Update(tipoDocIdentidad))
            {
                return RedirectToAction("Index");
            }
            return View(tipoDocIdentidad);
        }

        public ActionResult Delete(int id)
        {
            return View(_unit.TipoDocIdentidad.GetById(id));
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (_unit.TipoDocIdentidad.Delete(id))
            {
                return RedirectToAction("Index");
            }
            return View(_unit.TipoDocIdentidad.GetById(id));
        }
    }
}

Asistencia.Mvc/Controllers/TrabajadorController.cs
using Asistencia.Models;
using Asistencia.Repositories.Dapper.Asistencia;
using Asistencia.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asistencia.Mvc.Controllers
{
    public class TrabajadorController : BaseController
    {
        public TrabajadorController(IUnitOfWork unit): base(unit)
        {

        }
        // GET: Trabajador
        public ActionResult Index()
        {
            return View(_unit.Trabajador.GetList());
        }

        public ActionResult Create()
        {
            return View(new Trabajador());
        }

        [HttpPost]
        public ActionResult Create(Trabajador trabajador)
        {
            if (ModelState.IsValid)
            {
                _unit.Trabajador.Insert(trabajador);
                return RedirectToAction("Index");
            }
            return View(trabajador);
        }

        public ActionResult Edit(int id)
        {
            return View(_unit.Trabajador.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(Trabajador trabajador)
        {
            if (_unit.Trabajador.Update(trabajador))
            {
                return RedirectToAction("Index");
            }
            return View(trabajador);
        }

        public ActionResult Delete(int id)
        {
            return View(_unit.Trabajador.GetById(id));
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (_unit.Trabajador.Delete(id))
            {
                return RedirectToAction("Index");
            }
            return View(_unit.Trabajador.GetById(id));
        }
    }
}

Asistencia.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema Asistencia", "Register", "Movimiento", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">@Html.ActionLink("Registrar Asistencia", "Register", "Movimiento") <i class="fa fa-dashboard"></i> </li>
                    @*<li>@Html.ActionLink("Movimiento", "Register", "Movimiento")</li>*@
                    <li>@Html.ActionLink("Horarios", "Index", "Horario")</li>
                    <li>@Html.ActionLink("Marcaciones", "Index", "Marcacion")</li>
                    <li>@Html.ActionLink("Trabajadores", "Index", "Trabajador")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-square-o-down"></i> Maestros <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Oficinas", "Index", "Oficina")</li>
                            <li>@Html.ActionLink("Tipos Documento", "Index", "TipoDocIdentidad")</li>
                            <li>@Html.ActionLink("Tipos de trabajadores", "Index", "UsuarioMarcacion")</li>
                        </ul>
                    </li>
                </ul>


                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

    <!-- Page Specific Plugins -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
    <script src="js/morris/chart-data-morris.js"></script>
    <script src="js/tablesorter/jquery.tablesorter.js"></script>
    <script src="js/tablesorter/tables.js"></script>
    <script src="~/App_JS/reloj.js"></script>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>